### ISSUE TITLE
关于进程重启的问题

### ISSUE THREAD

**Issue by waterloopwm** [xtgxiso/WebWorker#13]
框架可以设置进程处理多少个请求后重启，但如果进程在重启，刚好有个请求过来，就会请求失败，workerman作者提出这个解决方案，先判断没有连接过来if (empty($worker->connections))，再重启进程，希望作者能集成进去

**Comment by waterloopwm** [comment]
你好，请问作者在吗

**Comment by xtgxiso** [comment]
在呢,可QQ联系聊下 124960772

**Comment by xtgxiso** [comment]
我验证过了，重启的时候不会有问题的
